Numpy

what: 科学计算库

why: 
- python list 在大数据速度慢，内存高，不能做向量、矩阵运算（循环多
- 快速、节省空间，提供数组化算术运算和高级别的广播功能
- 不需要循环计算

In [1]:
# ndaarray 多维数组对象
import numpy as np

# 列表转多维数组
lst1 = [1, 2, 3, 4, 5]
nd1 = np.array(lst1)
print(nd1)
print(type(nd1))
print(nd1.shape)

# 嵌套列表转多维数组
lst2 = [[1, 2, 3], [4, 5, 6]]
nd2 = np.array(lst2)
print(nd2)
print(type(nd2))
print(nd2.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [2]:
# random模块创建数组
print('生成形状为(2, 3)，值在(0,1)范围内的随机数组')
print(np.random.randn(2, 3), end='\n\n')

print('生成形状为(2, 3)，值在[0,1)范围，均匀分布的随机数组')
print(np.random.uniform(low=0, high=1, size=(2, 3)), end='\n\n')

print('生成形状为(2, 3)，值在[1,10)范围内的随机整数数组')
print(np.random.randint(low=1, high=10, size=(2, 3)), end='\n\n')

print('生成满足正态分布的随机数组')
print(np.random.normal(loc=0, scale=1, size=(3, 3)), end='\n\n')

生成形状为(2, 3)，值在(0,1)范围内的随机数组
[[ 0.20367071 -1.0663776  -1.30611004]
 [ 0.35164158  0.82811288 -1.26771485]]

生成形状为(2, 3)，值在[0,1)范围，均匀分布的随机数组
[[0.95931146 0.4608182  0.69851325]
 [0.733146   0.52921523 0.34310166]]

生成形状为(2, 3)，值在[1,10)范围内的随机整数数组
[[1 3 8]
 [2 5 6]]

生成满足正态分布的随机数组
[[-0.35138588  0.28971826 -1.33646448]
 [ 0.07280913  0.12979515 -0.30798639]
 [-0.05080173  0.37992314 -0.5287231 ]]



算术运算